"""new fields in user model

Revision ID: 851f18c3faca
Revises: 44ac21263150
Create Date: 2025-05-14 17:17:18.051071

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '851f18c3faca'
down_revision = '44ac21263150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    now = datetime.utcnow()
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=False, default=now))
        batch_op.alter_column('last_seen', nullable=False, default=now)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
